### ISSUE TITLE
flow_x and flow_y

### ISSUE THREAD

**Issue by ksharsha** [wanglimin/dense_flow#12]
Hi, I see that both the flow matrices flow_x as well as flow_y have non zero y and x components respectively. What do they actually signify?(Earlier I thought they are the flow values along the x and y direction, however since the flow in other axis is not zero I think they might have some other meaning)

**Comment by wanglimin** [comment]
It represents the motion field of each pixel, which could be decomposed into x- and y- direction.

**Comment by ksharsha** [comment]
Does that mean both flowx and flow y have the same values? But this isn't the case.

**Comment by wanglimin** [comment]
It should not be the same value for flow x and flow y. You could refer to the wikipedia for more information on optical flow:

https://en.wikipedia.org/wiki/Optical_flow

**Comment by ksharsha** [comment]
I do know what optical flow is but i am not able to understand what the flow_x and flow_y images represent. For a pixel in an image we have the displacement in both the x and y directions. How is this represented in the flow_ and flow_y images. I see that every pixel in flow_x as well as flow_y has two components. In normal optical we just have one image where every pixel has displacement in x and y direction. However here we have two images for the same. Hence I am unable to understand what is the difference between both the maps.

**Comment by wanglimin** [comment]
I can not understand what you mean "I see that every pixel in flow_x as well as flow_y has two components. "

In fact, the flow_x and flow_y images are gray image, where each pixel simply has a single value rather than two components.

Flow_x and flow_y are the quantization of displacement in x and y direction, respectively. In this sense, we separately quantized (i.e., from a float value to a integer in [0,255]) the value of x and y displacement , and the quantized result are stored in a jpg format. For details about the quantization, please see:

https://github.com/wanglimin/dense_flow/blob/master/denseFlow_gpu.cpp#L11
